os: linux

dist: xenial

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install codecov

install:
  - pip install tox-travis

script: tox

after_success:
  - codecov
