sudo: false

dist: trusty

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install codecov

install:
  - pip install tox-travis

script: tox

matrix:
  include:
  - python: "3.7"
    dist: xenial
    sudo: true

after_success:
  - codecov
