name: Lint
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
jobs:
  python_formatting_check:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dev dependencies
      run: pip install -r requirements/dev_requirements.txt
    - name: Check that Python files are formatted correctly
      run: black --check --diff .
