name: Lint
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
jobs:
  python_linting:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install lint dependencies
      run: pip install -r requirements/lint.txt
    - name: Check order of Python imports
      run: isort --check-only --diff --quiet .
    - name: Check formatting of Python files
      run: black --check --diff .
